export const MEMBER_AUTH ="/"
export const INFORMATION = "/information"
export const VERIFICATION = "verification"
export const PERSONAL_DETAILS = "personal-details"
export const BUSINESS_INFO = "business-info"
export const NEXT_OF_KIN = "next-of-kin"
